# Generated by Django 3.0.3 on 2020-08-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('dni', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('apellido_paterno', models.CharField(blank=True, max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True)),
                ('sexo', models.CharField(blank=True, max_length=100)),
                ('codigo_carrera', models.CharField(blank=True, max_length=100)),
                ('vigencia', models.IntegerField()),
            ],
        ),
    ]
