# Generated by Django 3.0.3 on 2020-08-28 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('curso', '0001_initial'),
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fecha_matricula', models.DateTimeField()),
                ('codigo_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.Curso')),
                ('id_estudiante',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.Estudiante')),
            ],
        ),
    ]
