# Generated by Django 3.0.3 on 2020-08-31 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0003_auto_20200831_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
