# Generated by Django 3.0.3 on 2020-08-31 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0005_auto_20200831_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='fecha_matricula',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
